# This file relates which dataset each selection should use for processing. The possible values for dataset are Muon, EGamma, or MET
TauTagPt55 = "Muon"
ZtoTauToMuProbeTrk = "Muon"
ZtoTauToEleProbeTrk = "EGamma"
MuonFiducial = "Muon"
ElectronFiducial = "EGamma"
TriggerAnalysis = "Muon"
BasicSelection = "MET"
DisTrkSelection = "MET"
ZtoEE = "EGamma"
ZtoMuMu = "Muon"
ElectronTagPt55 = "EGamma"
ZtoEleProbeTrk = "EGamma"
ZtoMuProbeTrk = "Muon"
MuonTagPt55 = "Muon"
