templates:
  - input: config_cfg_sim_template.py
    output: config_cfg.py
  - input: config_selections_template.py
    output: ../python/config.py
  - input: crab_sim_template.py
    output: crab_cfg.py
